// AI-generated by Claude Sonnet 5.5 (GitHub Copilot): flat config migrated from .eslintrc.json.
import js from "@eslint/js"
import react from "eslint-plugin-react"
import valtio from "eslint-plugin-valtio"
import globals from "globals"
import tseslint from "typescript-eslint"

export default tseslint.config(
    { ignores: ["build/"] },
    js.configs.recommended,
    ...tseslint.configs.recommended,
    react.configs.flat.recommended,
    valtio.configs["flat/recommended"],
    {
        languageOptions: {
            ecmaVersion: "latest",
            sourceType: "module",
            globals: globals.browser,
            parserOptions: { ecmaFeatures: { jsx: true } },
        },
        settings: { react: { version: "detect" } },
        rules: {
            "react/react-in-jsx-scope": "off",
            "react/prop-types": "off",
            eqeqeq: "error",
            "no-await-in-loop": "error",
            "no-duplicate-imports": ["error", { includeExports: true }],
            "no-new-native-nonconstructor": "error",
            camelcase: "error",
            curly: "error",
            "default-case": "error",
            "dot-notation": "error",
            "func-style": ["error", "declaration", { allowArrowFunctions: true }],
            "grouped-accessor-pairs": ["error", "getBeforeSet"],
            "no-lonely-if": "error",
            "prefer-const": "error",
            "arrow-spacing": "error",
            "block-spacing": "error",
            quotes: ["error", "double"],
            semi: ["error", "never"],
            "no-console": "warn",
            "react/jsx-sort-props": [
                "warn",
                {
                    shorthandFirst: true,
                    multiline: "last",
                    ignoreCase: true,
                    reservedFirst: true,
                    callbacksLast: true,
                },
            ],
        },
    },
)
