// AI-assisted by Claude Sonnet 5.5 (GitHub Copilot): moved MUI system props into sx, as part of the Vite/dependency migration.
// AI-generated by Claude Sonnet 4.5: css animation to adjust Streams' container size to make space for Drawer
import { Button, Stack, Toolbar } from "@mui/material"
import { useState } from "react"
import Alert from "./Alert"
import { removeAlert, useAlertState } from "./commons/alertState"
import { useStreamsState } from "./commons/streamsState"
import CookiesBanner from "./CookiesBanner"
import AppBar from "./features/app_bar/AppBar"
import Drawer from "./features/drawer/Drawer"
import { DrawerContent } from "./features/drawer/DrawerContentSwitch"
import Streams from "./features/stream_display/MainContent"
import PrivacyAndCookiesModal from "./PrivacyAndCookiesModal"
import Welcome from "./Welcome"

const App = () => {
    const [drawerContent, setDrawerContent] = useState(DrawerContent.None)
    const { message: alertMessage, severity: alertSeverity } = useAlertState()
    const { streams } = useStreamsState()
    const [privacyAndCookiesModalOpen, setPrivacyAndCookiesModalOpen] = useState(false)

    const DRAWER_WIDTH = "25vw"

    const handleCloseAlert = () => {
        removeAlert()
    }

    return (
        <Stack
            sx={{
                bgcolor: "black",
                height: "100vh",
                width: "100vw",
            }}
        >
            <AppBar
                drawerContentType={drawerContent}
                setDrawerContentType={setDrawerContent}
            />
            <Toolbar />
            <Drawer
                drawerContent={drawerContent}
                drawerWidth={DRAWER_WIDTH}
                handleDrawerClose={() => setDrawerContent(DrawerContent.None)}
            />
            {streams.length > 0 && (
                <Stack
                    sx={{
                        height: "100%",
                        marginLeft: drawerContent === DrawerContent.None ? 0 : DRAWER_WIDTH,

                        // this being higher than other elements helps preventing chrome from blocking autoplay
                        zIndex: (theme) => theme.zIndex.drawer + 2,

                        transition: (theme) =>
                            theme.transitions.create("margin-left", {
                                easing: theme.transitions.easing.sharp,
                                duration:
                                    drawerContent === DrawerContent.None
                                        ? theme.transitions.duration.leavingScreen
                                        : theme.transitions.duration.enteringScreen,
                            }),
                    }}
                >
                    <Streams />
                </Stack>
            )}
            {streams.length === 0 && <Welcome />}
            <Alert
                handleClose={handleCloseAlert}
                message={alertMessage}
                open={Boolean(alertMessage)}
                severity={alertSeverity}
            />
            <CookiesBanner />
            <PrivacyAndCookiesModal
                open={privacyAndCookiesModalOpen}
                onClose={() => setPrivacyAndCookiesModalOpen(false)}
            />

            {streams.length === 0 && (
                <Button
                    sx={{ position: "fixed", bottom: 16, right: 16 }}
                    variant="text"
                    onClick={() => setPrivacyAndCookiesModalOpen(true)}
                >
                    Privacy and Cookies
                </Button>
            )}
        </Stack>
    )
}

export default App
