// AI-generated by Claude Sonnet 4.5: css animation to adjust Streams' container size to make space for Drawer
import { Stack, Toolbar } from "@mui/material"
import { useState } from "react"
import Alert from "./Alert"
import { removeAlert, useAlertState } from "./commons/alertState"
import { useStreamsState } from "./commons/streamsState"
import AppBar from "./features/app_bar/AppBar"
import Drawer from "./features/drawer/Drawer"
import { DrawerContent } from "./features/drawer/DrawerContentSwitch"
import Streams from "./features/stream_display/MainContent"
import useYoutubeiFrameApi from "./hooks/useYoutubeiFrameApi"
import Welcome from "./Welcome"

const App = () => {
    const [drawerContent, setDrawerContent] = useState(DrawerContent.None)
    const { message: alertMessage, severity: alertSeverity } = useAlertState()
    const { streams } = useStreamsState()

    useYoutubeiFrameApi().loadYoutubeIframeApi()

    const DRAWER_WIDTH = "25vw"

    const handleCloseAlert = () => {
        removeAlert()
    }

    return (
        <Stack
            sx={{
                bgcolor: "black",
                height: "100vh",
                width: "100vw"
            }}>
            <AppBar
                drawerContentType={drawerContent}
                setDrawerContentType={setDrawerContent}
            />
            <Toolbar />
            <Drawer
                drawerContent={drawerContent}
                drawerWidth={DRAWER_WIDTH}
                handleDrawerClose={() => setDrawerContent(DrawerContent.None)}
            />
            {streams.length > 0 && (
                <Stack
                    sx={{
                        height: "100%",
                        marginLeft: drawerContent === DrawerContent.None ? 0 : DRAWER_WIDTH,

                        // this being higher than other elements helps preventing chrome from blocking autoplay
                        zIndex: (theme) => theme.zIndex.drawer + 2,

                        transition: (theme) =>
                            theme.transitions.create("margin-left", {
                                easing: theme.transitions.easing.sharp,
                                duration:
                                    drawerContent === DrawerContent.None
                                        ? theme.transitions.duration.leavingScreen
                                        : theme.transitions.duration.enteringScreen,
                            })
                    }}>
                    <Streams />
                </Stack>
            )}
            {streams.length === 0 && <Welcome />}
            <Alert
                handleClose={handleCloseAlert}
                message={alertMessage}
                open={Boolean(alertMessage)}
                severity={alertSeverity}
            />
        </Stack>
    )
}

export default App
