// AI-generated by Claude Sonnet 4.5: css animation to adjust Streams' container size to make space for Drawer
import { Stack, Toolbar } from "@mui/material"
import { useState } from "react"
import Alert from "./Alert"
import { removeAlert, useAlertState } from "./commons/alertState"
import AppBar from "./features/app_bar/AppBar"
import Drawer from "./features/drawer/Drawer"
import { DrawerContent } from "./features/drawer/DrawerContentSwitch"
import Streams from "./features/main_content/MainContent"
import Welcome from "./Welcome"

const App = () => {
    const [drawerContent, setDrawerContent] = useState(DrawerContent.None)
    const firstTimeVisitor = isIfFirstTimeVisitor()
    const { message: alertMessage, severity: alertSeverity } = useAlertState()

    const DRAWER_WIDTH = "25vw"

    const handleCloseAlert = () => {
        removeAlert()
    }

    return (
        <Stack
            bgcolor="black"
            height="100vh"
            width="100vw"
        >
            <AppBar
                drawerContentType={drawerContent}
                setDrawerContentType={setDrawerContent}
            />
            <Toolbar />
            <Drawer
                drawerContent={drawerContent}
                drawerWidth={DRAWER_WIDTH}
                handleDrawerClose={() => setDrawerContent(DrawerContent.None)}
            />
            <Stack
                height="100%"
                sx={{
                    marginLeft: drawerContent === DrawerContent.None ? 0 : DRAWER_WIDTH,
                    zIndex: (theme) => theme.zIndex.drawer + 2, // this being higher than other elements helps preventing chrome from blocking autoplay
                    transition: (theme) =>
                        theme.transitions.create("margin-left", {
                            easing: theme.transitions.easing.sharp,
                            duration:
                                drawerContent === DrawerContent.None
                                    ? theme.transitions.duration.leavingScreen
                                    : theme.transitions.duration.enteringScreen,
                        }),
                }}
            >
                <Streams />
                {firstTimeVisitor && <Welcome />}
            </Stack>
            <Alert
                handleClose={handleCloseAlert}
                message={alertMessage}
                open={Boolean(alertMessage)}
                severity={alertSeverity}
            />
        </Stack>
    )
}

const isIfFirstTimeVisitor = () => {
    const hasVisitedSiteBefore = localStorage.getItem("hasVisitedSiteBefore")

    if (!hasVisitedSiteBefore) {
        localStorage.setItem("hasVisitedSiteBefore", "true")
        return true
    }

    return false
}

export default App
