// Module AI-generated by GitHub Copilot
import ExpandMoreIcon from "@mui/icons-material/ExpandMore"
import {
    Box,
    Button,
    Checkbox,
    FormControlLabel,
    IconButton,
    Paper,
    Stack,
    Typography,
} from "@mui/material"
import { useState } from "react"
import CookiesConsent, { CookieChoice, useCookiesConsent } from "./CookiesConsent"

const CookiesBanner = () => {
    const essentialChoice = useCookiesConsent("essential")
    const twitchChoice = useCookiesConsent("twitch")
    const youtubeChoice = useCookiesConsent("youtube")
    const [expanded, setExpanded] = useState(false)
    const [allowTwitch, setAllowTwitch] = useState(twitchChoice === "accept")
    const [allowYoutube, setAllowYoutube] = useState(youtubeChoice === "accept")

    if (essentialChoice !== null && twitchChoice !== null && youtubeChoice !== null) {
        return null
    }

    const saveChoices = (twitchConsent: CookieChoice, youtubeConsent: CookieChoice) => {
        CookiesConsent.set("twitch", twitchConsent)
        CookiesConsent.set("youtube", youtubeConsent)
        CookiesConsent.set("essential", "accept")
    }

    const saveAll = (choice: CookieChoice) => {
        saveChoices(choice, choice)
    }

    const savePreferences = () => {
        saveChoices(allowTwitch ? "accept" : "reject", allowYoutube ? "accept" : "reject")
    }

    return (
        <Paper
            square
            aria-label="Cookie consent"
            component="aside"
            elevation={1}
            role="region"
            sx={{
                bottom: 0,
                left: 0,
                padding: 2,
                position: "fixed",
                width: "100%",
                zIndex: (theme) => theme.zIndex.snackbar + 1,
            }}
        >
            <Stack
                direction={{ xs: "column", sm: "row" }}
                sx={{ alignItems: { xs: "stretch", sm: "center" }, gap: 2.5 }}
            >
                <Box sx={{ flex: 1, minWidth: 0 }}>
                    <Typography
                        sx={{ fontWeight: 700, mb: 0.5 }}
                        variant="subtitle1"
                    >
                        Your cookie choices
                    </Typography>
                    <Typography
                        color="text.secondary"
                        variant="body2"
                    >
                        We use an essential cookies for authenticating in Twitch-related
                        functionalities. By connecting your Twitch account to Tourneystreams you
                        consent to their use. Opening Twitch and YouTube streams will load their
                        cookies; you must consent to receiving them in order to watch streams.
                    </Typography>
                </Box>
                <Stack
                    direction="row"
                    sx={{ alignItems: "center", gap: 0.5 }}
                >
                    <Button
                        sx={{ color: "text.primary", flex: 1, whiteSpace: "nowrap" }}
                        variant="outlined"
                        onClick={() => saveAll("reject")}
                    >
                        Reject all
                    </Button>
                    <Button
                        color="primary"
                        sx={{ flex: 1, whiteSpace: "nowrap" }}
                        variant="contained"
                        onClick={() => saveAll("accept")}
                    >
                        Accept all
                    </Button>
                    <IconButton
                        aria-expanded={expanded}
                        aria-label={expanded ? "Hide cookie choices" : "Show cookie choices"}
                        sx={{ color: "text.primary" }}
                        title={expanded ? "Hide cookie choices" : "Show cookie choices"}
                        onClick={() => setExpanded((isExpanded) => !isExpanded)}
                    >
                        <ExpandMoreIcon sx={{ transform: expanded ? "rotate(180deg)" : "none" }} />
                    </IconButton>
                </Stack>
            </Stack>
            {expanded && (
                <Box
                    sx={{
                        borderTop: "1px solid rgba(255, 255, 255, 0.16)",
                        mt: 2,
                        pt: 1.5,
                    }}
                >
                    <Typography
                        sx={{ fontWeight: 700, mb: 1 }}
                        variant="subtitle2"
                    >
                        Cookie preferences
                    </Typography>
                    <Stack sx={{ gap: 0.5 }}>
                        <FormControlLabel
                            label="Essential"
                            sx={{ ml: 0 }}
                            control={
                                <Checkbox
                                    checked
                                    disabled
                                />
                            }
                        />
                        <FormControlLabel
                            label="Twitch third-party cookies"
                            sx={{ ml: 0 }}
                            control={
                                <Checkbox
                                    checked={allowTwitch}
                                    onChange={(event) => setAllowTwitch(event.target.checked)}
                                />
                            }
                        />
                        <FormControlLabel
                            label="YouTube third-party cookies"
                            sx={{ ml: 0 }}
                            control={
                                <Checkbox
                                    checked={allowYoutube}
                                    onChange={(event) => setAllowYoutube(event.target.checked)}
                                />
                            }
                        />
                    </Stack>
                    <Stack sx={{ alignItems: "flex-end", mt: 1 }}>
                        <Button
                            color="primary"
                            variant="contained"
                            onClick={savePreferences}
                        >
                            Save choices
                        </Button>
                    </Stack>
                </Box>
            )}
        </Paper>
    )
}

export default CookiesBanner
