// Module generated by GitHub Copilot
import { useSyncExternalStore } from "react"

export type CookieType = "essential" | "youtube" | "twitch"
export type CookieChoice = "accept" | "reject"

class CookiesConsent {
    private static listeners = new Map<CookieType, Set<() => void>>()
    private static subscriptions = new Map<CookieType, (listener: () => void) => () => void>()

    static set(cookie: CookieType, choice: CookieChoice) {
        localStorage.setItem(cookie, choice)
        this.listeners.get(cookie)?.forEach((listener) => listener())
    }

    static get(cookie: CookieType): CookieChoice | null {
        const choice = localStorage.getItem(cookie)
        return choice === "accept" || choice === "reject" ? choice : null
    }

    static subscribe(cookie: CookieType) {
        const existingSubscription = this.subscriptions.get(cookie)
        if (existingSubscription) {
            return existingSubscription
        }

        const subscription = (listener: () => void) => {
            const listeners = this.listeners.get(cookie) ?? new Set<() => void>()
            listeners.add(listener)
            this.listeners.set(cookie, listeners)

            const handleStorage = (event: StorageEvent) => {
                if (event.key === cookie || event.key === null) {
                    listener()
                }
            }
            window.addEventListener("storage", handleStorage)

            return () => {
                listeners.delete(listener)
                window.removeEventListener("storage", handleStorage)
                if (listeners.size === 0) {
                    this.listeners.delete(cookie)
                }
            }
        }

        this.subscriptions.set(cookie, subscription)
        return subscription
    }
}

export const useCookiesConsent = (cookie: CookieType) =>
    useSyncExternalStore(
        CookiesConsent.subscribe(cookie),
        () => CookiesConsent.get(cookie),
        () => null,
    )

export default CookiesConsent
